// The tree the browser dev page opens. Kept tiny; real fixtures live in tests/.
export const sampleFiles: Record<string, string> = {
  '/home/dev/notes/README.md': [
    '# MD-BOSS',
    '',
    'A markdown viewer and editor that looks like paper.',
    '',
    '> [!NOTE]',
    '> Rendered entirely offline by the bundled `marked.js`.',
    '',
    '## Keyboard',
    '',
    '| Key | Action |',
    '|---|---|',
    '| ⌘N | new file |',
    '| ⌘P | go to file |',
    '',
    '- [x] sidebar',
    '- [ ] editor',
    '',
    '```js',
    'const answer = 42',
    '```',
    '',
  ].join('\n'),
  '/home/dev/notes/plan.md': '# Plan\n\nSecond document.\n',
  '/home/dev/notes/data.csv': 'a,b\n1,2\n',
  '/home/dev/notes/guide/setup.md': '# Setup\n\nInside a folder.\n',
  '/home/dev/notes/guide/deep/more.md': '# More\n\nTwo levels down.\n',
  '/home/dev/notes/src/main.swift': 'print("not a document")\n',
  '/home/dev/notes/node_modules/pkg/README.md': '# vendored\n',
}
